#:schema node_modules/wrangler/config-schema.json
name = "hono-todo-app"
main = "src/index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "HONO_TODO", preview_id = "40eb37fd7c764b9a93ab3d316da013fa", id = "930874bad2ee4b75bfbadae09d5694cd" },
]
